window.BeyondFeedData = {
  categories: [
    { slug: 'mind', label: 'Instagram & The Mind', short: 'Mind', query: 'social media attention', description: 'Comparison, attention, self-expression and the inspiration we find in a shared visual world.', color: 'coral' },
    { slug: 'creativity', label: 'Creativity & Communities', short: 'Creativity', query: 'creativity online communities', description: 'Creators, niche communities and the collaborations that make discovery feel human.', color: 'lime' },
    { slug: 'business', label: 'Instagram for Business', short: 'Business', query: 'creator economy digital business', description: 'How creators and small businesses turn a digital presence into a place to connect.', color: 'blue' },
    { slug: 'habits', label: 'Healthy Digital Habits', short: 'Habits', query: 'digital wellbeing technology', description: 'Mindful scrolling, intentional use and boundaries for a healthier relationship with the feed.', color: 'yellow' },
  ],
  fallbackArticles: [
    { id: 'demo-1', slug: 'the-post-post-instagram', title: 'The Post-Post Instagram', description: 'How Instagram posting culture is moving from polished performance toward smaller, more honest audiences.', body: 'The pressure to make every Instagram post look like proof of a perfect life has softened. Photo dumps, quieter captions and Close Friends stories make room for the unfinished, the ordinary and the people who already know the context. The feed is still a stage, and comparison has not disappeared, but posting can now feel less like a performance review and more like choosing what is worth sharing.', category: 'Instagram & The Mind', categorySlug: 'mind', author: 'Maya Chen', readTime: '6 min read', image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=85', source: 'Beyond the Feed demo', sourceUrl: 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', publishedAt: '2023-05-31', featured: true },
    { id: 'demo-2', slug: 'your-niche-is-already-here', title: 'Your Niche Is Already Here', description: 'Reels, carousels and Instagram communities are turning small interests into places to learn, make and belong.', body: 'Instagram discovery can begin with a Reel, continue through a carousel and end in a page devoted to an interest you did not know had a community. That path can become a rabbit hole, but it can also introduce a beginner to a creative practice, a collaborator or a language for something they already love.', category: 'Creativity & Communities', categorySlug: 'creativity', author: 'Ari Okafor', readTime: '8 min read', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=85', source: 'Beyond the Feed demo', sourceUrl: 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', publishedAt: '2023-05-31' },
    { id: 'demo-3', slug: 'the-link-in-bio-is-a-business-model', title: 'The Link in Bio Is a Business Model', description: 'How creators and small businesses turn discovery, collaborations and visual storytelling into a storefront.', body: 'For a small business or independent creator, Instagram can be a shop window, portfolio and first conversation in one place. A Reel can introduce the process, a carousel can answer a customer question and a collaboration can bring two communities together.', category: 'Instagram for Business', categorySlug: 'business', author: 'Lena Ortiz', readTime: '7 min read', image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85', source: 'Beyond the Feed demo', sourceUrl: 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', publishedAt: '2023-05-31' },
    { id: 'demo-4', slug: 'a-feed-you-can-live-with', title: 'A Feed You Can Live With', description: 'How intentional scrolling and private sharing can lower the pressure to be always on.', body: 'A healthier Instagram practice starts with deciding what the app is for. Follow accounts that teach or delight you, use private sharing when a moment belongs to a smaller circle, and take a break when the feed turns comparison into background noise.', category: 'Healthy Digital Habits', categorySlug: 'habits', author: 'Priya Shah', readTime: '6 min read', image: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=900&q=85', source: 'Beyond the Feed demo', sourceUrl: 'https://about.fb.com/news/2024/01/teen-protections-age-appropriate-experiences-on-our-apps/', publishedAt: '2024-01-09' },
  ],
}