window.BeyondFeedData = {
  categories: [
    { slug: 'creativity', label: 'Creativity', short: 'Creativity', query: 'Instagram creativity creators visual culture', description: 'How Instagram changes what we make, notice and call creative.', color: 'coral' },
    { slug: 'communities', label: 'Online Communities', short: 'Communities', query: 'Instagram online communities niche interests', description: 'The shared interests, hashtags and conversations that turn followers into belonging.', color: 'lime' },
    { slug: 'business', label: 'Instagram for Business', short: 'Business', query: 'creator economy digital business', description: 'How creators and small businesses turn a digital presence into a place to connect.', color: 'blue' },
    { slug: 'habits', label: 'Healthy Digital Habits', short: 'Habits', query: 'digital wellbeing technology', description: 'Mindful scrolling, intentional use and boundaries for a healthier relationship with the feed.', color: 'yellow' },
    { slug: 'trends', label: 'Trends', short: 'Trends', query: 'Instagram trends viral reels culture', description: 'The sounds, formats and shared moments that move from one screen to millions.', color: 'coral' },
    { slug: 'expression', label: 'Connection & Expression', short: 'Expression', query: 'Instagram self expression connection stories', description: 'How we share ordinary lives, build closeness and express ourselves online.', color: 'lime' },
  ],
  fallbackArticles: [
    { id: 'demo-1', slug: 'how-instagram-changed-what-we-call-creativity', title: 'How Instagram Changed What We Call Creativity', description: 'From polished grids to quick experiments, the platform has widened the circle of people who get to make and share.', body: 'Instagram made creativity feel less like a finished object and more like a daily practice. A photo, a carousel explaining a process or a Reel built around a sound can all become creative work when people find a way to give an idea their own texture. The pressure to perform is real, but so is the permission to begin before everything is perfect. The most interesting work often lives in that space between personal expression and a format the feed can carry.', category: 'Creativity', categorySlug: 'creativity', author: 'Maya Chen', readTime: '6 min read', image: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?auto=format&fit=crop&w=1200&q=85', source: 'Beyond the Feed', sourceUrl: 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', publishedAt: '2024-05-31', featured: true },
    { id: 'demo-2', slug: 'from-followers-to-belonging', title: 'From Followers to Belonging: The New Internet Communities', description: 'Why niche Instagram spaces can turn a passing interest into a place to learn, contribute and feel recognized.', body: 'A community can begin with one Reel, a shared hashtag or a comment from someone who understands the reference. Over time, repeated names become familiar, advice moves between strangers and a niche interest starts to feel like a room with the door open. These spaces are not a replacement for every offline relationship, but they give people new ways to find peers, mentors and collaborators around the things they care about.', category: 'Online Communities', categorySlug: 'communities', author: 'Ari Okafor', readTime: '8 min read', image: 'https://images.unsplash.com/photo-1492684223066-81342ee5ff30?auto=format&fit=crop&w=900&q=85', source: 'Beyond the Feed', sourceUrl: 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', publishedAt: '2024-05-31' },
    { id: 'demo-3', slug: 'how-instagram-turned-small-businesses-into-brands', title: 'How Instagram Turned Small Businesses Into Brands', description: 'For independent makers, the feed is part shop window, part studio visit and part first conversation.', body: 'A small business no longer has to look established before it can be discovered. A home baker can show the hands behind the recipe, a designer can explain a material choice and a neighborhood shop can make regular customers feel like insiders. Instagram turns those small moments into a recognizable point of view, which is why the strongest business accounts sell more than products: they invite people into a story.', category: 'Instagram for Business', categorySlug: 'business', author: 'Lena Ortiz', readTime: '7 min read', image: 'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=900&q=85', source: 'Beyond the Feed', sourceUrl: 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', publishedAt: '2024-05-31' },
    { id: 'demo-4', slug: 'why-we-open-instagram-without-knowing-why', title: 'Why We Open Instagram Without Knowing Why', description: 'The familiar gesture of checking the feed can become a cue, a pause and eventually part of the shape of a day.', body: 'Sometimes the app is not answering a question; it is filling a gap between two things. The unlock, tap and scroll offer a tiny burst of novelty, which makes the habit easy to repeat even when we cannot remember what we came to see. Noticing the cue is more useful than treating every scroll as a failure. A little friction, a deliberate pause or a saved list of things to do offline can give the moment another ending.', category: 'Healthy Digital Habits', categorySlug: 'habits', author: 'Priya Shah', readTime: '6 min read', image: 'https://images.unsplash.com/photo-1499209974431-9dddcece7f88?auto=format&fit=crop&w=900&q=85', source: 'Beyond the Feed', sourceUrl: 'https://about.fb.com/news/2024/01/teen-protections-age-appropriate-experiences-on-our-apps/', publishedAt: '2024-06-09' },
    { id: 'demo-5', slug: 'why-instagram-trends-spread-so-fast', title: 'Why Instagram Trends Spread So Fast', description: 'A shared audio or visual format gives millions of people a common starting point, then each person adds a local accent.', body: 'Instagram trends move quickly because participation is built into the format. The sound is already there, the template is recognizable and the invitation is simple: try it your way. What begins as repetition can become a cultural conversation when different communities adapt the same cue to their own humor, language and everyday lives. The trend matters less as a single viral moment than as a record of how people make meaning together.', category: 'Trends', categorySlug: 'trends', author: 'Noah Williams', readTime: '5 min read', image: 'https://images.unsplash.com/photo-1611162616305-c69b3fa7fbe0?auto=format&fit=crop&w=900&q=85', source: 'Beyond the Feed', sourceUrl: 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', publishedAt: '2024-06-14' },
    { id: 'demo-6', slug: 'from-photos-to-stories', title: 'From Photos to Stories: How We Share Our Lives Online', description: 'Instagram changed everyday updates from occasional announcements into a running language of connection and expression.', body: 'A Story can be a finished photograph, a blurry plate of food, a song lyric or a message that only makes sense to a few people. Its temporary shape lowers the stakes while making sharing feel more frequent and immediate. We use these fragments to say I was here, I thought of you and this is what my day looked like. The result is a social language built from small signals rather than formal updates.', category: 'Connection & Expression', categorySlug: 'expression', author: 'Samira Patel', readTime: '6 min read', image: 'https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=900&q=85', source: 'Beyond the Feed', sourceUrl: 'https://about.instagram.com/blog/announcements/instagram-ranking-explained', publishedAt: '2024-06-18' },
  ],
}